name: Build Resume

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          npm i
          npm run build-site
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          folder: dist
          branch: gh-pages
